# Generated by Django 5.2.17 on 2026-09-09 15:04

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Design',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='نام')),
                ('active', models.BooleanField(default=True, verbose_name='فعال')),
                ('code', models.CharField(blank=True, max_length=40, verbose_name='کد')),
            ],
            options={
                'verbose_name': 'طرح',
                'verbose_name_plural': 'طرح\u200cها',
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Factory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='نام')),
                ('active', models.BooleanField(default=True, verbose_name='فعال')),
            ],
            options={
                'verbose_name': 'کارخانه',
                'verbose_name_plural': 'کارخانه\u200cها',
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='نام')),
                ('active', models.BooleanField(default=True, verbose_name='فعال')),
                ('rank', models.PositiveIntegerField(unique=True, verbose_name='ترتیب درجه')),
                ('color', models.CharField(default='#159b9a', max_length=7, validators=[django.core.validators.RegexValidator('^#[0-9a-fA-F]{6}$', 'رنگ شش\u200cرقمی معتبر وارد کنید.')], verbose_name='رنگ نمودار')),
            ],
            options={
                'verbose_name': 'درجه',
                'verbose_name_plural': 'درجات',
                'ordering': ['rank'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Production',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='تاریخ تولید')),
                ('area', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='متراژ (مترمربع)')),
                ('notes', models.TextField(blank=True, max_length=2000, verbose_name='توضیحات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='productions', to=settings.AUTH_USER_MODEL, verbose_name='ثبت\u200cکننده')),
                ('design', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='production.design', verbose_name='طرح')),
                ('factory', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='production.factory', verbose_name='کارخانه')),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='production.grade', verbose_name='درجه')),
            ],
            options={
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Audit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', 'ایجاد'), ('update', 'ویرایش'), ('delete', 'حذف')], max_length=12)),
                ('at', models.DateTimeField(auto_now_add=True)),
                ('before', models.JSONField(default=dict)),
                ('after', models.JSONField(default=dict)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('production', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='production.production')),
            ],
            options={
                'ordering': ['-at'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'مدیر سامانه'), ('entry', 'کاربر ثبت تولید'), ('viewer', 'مدیر گزارش\u200cگیر')], default='viewer', max_length=10, verbose_name='نقش')),
                ('factories', models.ManyToManyField(blank=True, to='production.factory', verbose_name='کارخانه\u200cهای مجاز')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('width', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='عرض (سانتی\u200cمتر)')),
                ('length', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='طول (سانتی\u200cمتر)')),
                ('active', models.BooleanField(default=True, verbose_name='فعال')),
            ],
            options={
                'verbose_name': 'سایز',
                'verbose_name_plural': 'سایزها',
                'ordering': ['width', 'length'],
                'constraints': [models.UniqueConstraint(fields=('width', 'length'), name='unique_tile_size'), models.CheckConstraint(condition=models.Q(('length__gt', 0), ('width__gt', 0)), name='positive_size')],
            },
        ),
        migrations.AddField(
            model_name='production',
            name='size',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='production.size', verbose_name='سایز'),
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.UUIDField()),
                ('digest', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='production',
            index=models.Index(fields=['factory', 'date'], name='production__factory_7ed544_idx'),
        ),
        migrations.AddIndex(
            model_name='production',
            index=models.Index(fields=['design', 'size', 'grade'], name='production__design__31c2ae_idx'),
        ),
        migrations.AddIndex(
            model_name='production',
            index=models.Index(fields=['deleted_at', 'date'], name='production__deleted_a76b76_idx'),
        ),
        migrations.AddConstraint(
            model_name='production',
            constraint=models.CheckConstraint(condition=models.Q(('area__gt', 0)), name='positive_production_area'),
        ),
        migrations.AddConstraint(
            model_name='submission',
            constraint=models.UniqueConstraint(fields=('user', 'key'), name='unique_submission'),
        ),
    ]
