# Generated by Django 6.0 on 2026-09-09 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='production',
            name='positive_production_area',
        ),
        migrations.RemoveIndex(
            model_name='production',
            name='production__design__31c2ae_idx',
        ),
        migrations.RemoveField(
            model_name='production',
            name='design',
        ),
        migrations.DeleteModel(
            name='Design',
        ),
    ]
