# Generated by Django 6.0 on 2026-09-10 08:33

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0002_remove_production_positive_production_area_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TechnicalType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='نام فنی')),
                ('description', models.TextField(blank=True, verbose_name='شرح')),
            ],
            options={
                'verbose_name': 'نوع فنی',
                'verbose_name_plural': 'انواع فنی',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProductionImportBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='تاریخ تولید')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان بارگذاری')),
                ('original_file', models.FileField(upload_to='imports/', verbose_name='فایل اکسِل')),
                ('sheet_name', models.CharField(blank=True, max_length=200, verbose_name='نام شیت')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='توکن')),
                ('factory', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='production.factory', verbose_name='کارخانه')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='بارگذار')),
            ],
            options={
                'verbose_name': 'دسته بارگذاری تولید از اکسل',
                'verbose_name_plural': 'دسته\u200cهای بارگذاری تولید از اکسل',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductionImportRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('excel_row', models.PositiveIntegerField(verbose_name='ردیف اکسل')),
                ('raw_description', models.TextField(verbose_name='شرح خام')),
                ('parsed_description', models.TextField(blank=True, verbose_name='شرح پردازش\u200cشده')),
                ('area', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='متراژ')),
                ('notes', models.CharField(blank=True, max_length=200, verbose_name='یادداشت')),
                ('status', models.CharField(choices=[('pending', 'در انتظار'), ('error', 'خطا'), ('ok', 'تأیید شده')], default='pending', max_length=20, verbose_name='وضعیت')),
                ('error_message', models.TextField(blank=True, verbose_name='پیام خطا')),
                ('edited_data', models.JSONField(blank=True, null=True, verbose_name='داده\u200cهای اصلاح\u200cشده')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='production.productionimportbatch', verbose_name='دسته بارگذاری')),
                ('grade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='production.grade', verbose_name='درجه')),
                ('size', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='production.size', verbose_name='سایز')),
                ('technical_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='production.technicaltype', verbose_name='نوع فنی')),
            ],
            options={
                'verbose_name': 'ردیف بارگذاری تولید',
                'verbose_name_plural': 'ردیف\u200cهای بارگذاری تولید',
                'ordering': ['excel_row'],
            },
        ),
        migrations.AddField(
            model_name='production',
            name='technical_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='production.technicaltype', verbose_name='نوع فنی'),
        ),
    ]
