# Generated by Django 6.0 on 2026-09-11 09:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0003_technicaltype_productionimportbatch_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='productionimportbatch',
            name='confirmed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='زمان ثبت نهایی'),
        ),
        migrations.AddField(
            model_name='productionimportbatch',
            name='confirmed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_batches', to=settings.AUTH_USER_MODEL, verbose_name='تأییدکننده'),
        ),
        migrations.AddField(
            model_name='productionimportbatch',
            name='file_hash',
            field=models.CharField(blank=True, max_length=64, verbose_name='هش فایل'),
        ),
        migrations.AddField(
            model_name='productionimportbatch',
            name='status',
            field=models.CharField(choices=[('pending', 'در انتظار بررسی'), ('confirmed', 'ثبت شده')], default='pending', max_length=20, verbose_name='وضعیت'),
        ),
        migrations.AddField(
            model_name='productionimportrow',
            name='extracted_grade_code',
            field=models.CharField(blank=True, max_length=50, verbose_name='کد درجه استخراج\u200cشده'),
        ),
        migrations.AddField(
            model_name='productionimportrow',
            name='extracted_length',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='طول استخراج\u200cشده'),
        ),
        migrations.AddField(
            model_name='productionimportrow',
            name='extracted_piece_area',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='مساحت قطعه استخراج\u200cشده'),
        ),
        migrations.AddField(
            model_name='productionimportrow',
            name='extracted_technical_type_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='نوع فنی استخراج\u200cشده'),
        ),
        migrations.AddField(
            model_name='productionimportrow',
            name='extracted_width',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='عرض استخراج\u200cشده'),
        ),
        migrations.AddField(
            model_name='productionimportrow',
            name='is_reversed_size',
            field=models.BooleanField(default=False, verbose_name='تطبیق سایز معکوس'),
        ),
        migrations.AddField(
            model_name='productionimportrow',
            name='production',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='import_rows', to='production.production', verbose_name='تولید نهایی'),
        ),
        migrations.AddField(
            model_name='productionimportrow',
            name='production_quantity',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='جمع تولید'),
        ),
    ]
