# Generated by Django 5.2.17 on 2026-09-11 11:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0004_productionimportbatch_confirmed_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='productionimportrow',
            name='source_errors',
            field=models.JSONField(blank=True, default=list, verbose_name='خطاهای منبع فایل'),
        ),
        migrations.AlterField(
            model_name='productionimportrow',
            name='extracted_piece_area',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='ضریب مساحت واحد تولید استخراج\u200cشده'),
        ),
        migrations.AddConstraint(
            model_name='productionimportbatch',
            constraint=models.UniqueConstraint(condition=models.Q(('file_hash__gt', ''), ('status', 'confirmed')), fields=('factory', 'date', 'file_hash', 'sheet_name'), name='unique_confirmed_import_batch'),
        ),
    ]
